export const INCREMENT_REQUESTED = 'INCREMENT_REQUESTED'
export const INCREMENT = 'INCREMENT'
export const DECREMENT_REQUESTED = 'DECREMENT_REQUESTED'
export const DECREMENT = 'DECREMENT'

export const REQUESTED_EMPLOYEE_LIST = 'REQUESTED_EMPLOYEE_LIST'
export const GET_EMPLOYEE_LIST = 'GET_EMPLOYEE_LIST'
export const REQUEST_ERROR_EMPLOYEE_LIST = 'REQUEST_ERROR_EMPLOYEE_LIST'
export const CLEAR_EMPLOYEE_LIST = 'CLEAR_EMPLOYEE_LIST'

export const REQUESTED_EMPLOYEE_DETAIL = 'REQUESTED_EMPLOYEE_DETAIL'
export const GET_EMPLOYEE_DETAIL = 'GET_EMPLOYEE_DETAIL'
export const REQUEST_ERROR_EMPLOYEE_DETAIL = 'REQUEST_ERROR_EMPLOYEE_DETAIL'
export const CLEAR_EMPLOYEE_DETAIL = 'CLEAR_EMPLOYEE_DETAIL'
