export const HOME_PAGE_URL = '/'
export const ABOUT_PAGE_URL = '/about-us'
export const ANTD_DEMO_PAGE_URL = '/antd-demo'
export const EMPLOYEE_DETAIL_URL = '/employee'
export const EMPLOYEE_LIST_URL = '/empolyees'
